### ISSUE TITLE
warning when using Sphinx's -j option

### ISSUE THREAD

**Issue by EricFromCanada** [michaeljones/breathe#141]
As of 1.2 sphinx-build supports the -j option to distribute the build over multiple processes. It's considered experimental, partly because plugins need to specifically declare support for it. Currently, a project using breathe and `-j 2` throws this warning: 

```
WARNING: the breathe extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

It looks like returning `parallel_read_safe : True` from `setup()` is all that's required to take care of the message, but are there any other changes needed to parallelize breathe?

**Comment by ishitatsuyuki** [comment]
Any updates? Is there anything I can help?

**Comment by vitaut** [comment]
@ishitatsuyuki As Eric wrote, we need to implement [env-merge-info](http://sphinx.readthedocs.org/en/latest/extdev/appapi.html?highlight=env-merge-info#event-env-merge-info). If you could contribute, that would be awesome. The `sphinx.ext.todo` extension can be used as an example.

**Comment by melvinvermeeren** [comment]
I just pushed a small change to branch `141-warning-when-using-sphinx-j-option` that returns true for `parallel_read_safe`. For the few small projects I have this seems to work fine.

@mbolivar I also built the zephyr docs zephyrproject-rtos/zephyr#6823. I compared output with `git diff --no-index` between a single-threaded build and a 8-threaded build. Small differences in toctree structure did exist but everything else was working perfectly with a vastly improved build time.

The only issue is that some logging errors are emitted during the build, such as:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/site-packages/sphinx/util/logging.py", line 445, in format
    message = super(ColorizeFormatter, self).format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/site-packages/sphinx/util/logging.py", line 96, in getMessage
    message = super(SphinxWarningLogRecord, self).getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/sphinx-build", line 11, in <module>
    load_entry_point('Sphinx==1.7.3', 'console_scripts', 'sphinx-build')()
  File "/usr/lib/python3.6/site-packages/sphinx/cmd/build.py", line 38, in main
    return build_main(argv)
  File "/usr/lib/python3.6/site-packages/sphinx/cmd/build.py", line 23, in build_main
    return cmdline.main(argv)  # type: ignore
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 351, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/lib/python3.6/site-packages/sphinx/util/logging.py", line 240, in pending_warnings
    memhandler.flushTo(logger)
  File "/usr/lib/python3.6/site-packages/sphinx/util/logging.py", line 206, in flushTo
    logger.handle(record)
Message: "Duplicate declaration, also defined in 'subsystems/sensor'.\nName of declaration is 'sensor_value'."
Arguments: ('api/io_interfaces',)
```

It is not obvious whether this is an issue in Breathe or Sphinx itself, I will look into it soon.

**Comment by melvinvermeeren** [comment]
The issue has been located in Sphinx and a PR with a fix has been sent upstream. Using an old version of Sphinx will still work, you can (based upon my testing) safely ignore the logging errors. The output is still correct. I will create a PR for breathe with the changes in branch 141 now, I think it is safe to merge.

**Comment by mbolivar** [comment]
Awesome, thanks for the update. I'll forward the info to the docs maintainers at Zephyr and hopefully we can take advantage of parallel builds from now on.

**Comment by melvinvermeeren** [comment]
@mbolivar 4.8.0 will be released in a bit, which will also contain this. In case you encounter issues with `-j` please open a new issue. Thanks!
