### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '_build/doctrees/index.doctree'

### ISSUE THREAD

**Issue by andrewholgate** [michaeljones/breathe#143]
Hello,

I am just getting started with Doxgen, Breathe and Sphinx and I cannot understand the correct way to configure Sphinx to correctly generate HTML from the generated XML files.

I am attempting to document a Drupal project (PHP). I have done the following:
1) Configured `doxygen.config`:

```
GENERATE_XML           = YES
XML_OUTPUT             = doxygen
```

2) Run `doxygen doxygen.config` and can confirm that all of the .xml files are in `./doxygen/`

3) Configured `conf.py`

```
sys.path.append( "/usr/local/lib/python2.7/dist-packages/breathe/" )
extensions = [ 'breathe' ]
breathe_projects = {
    "myproject":"/home/vagrant/itc/releases/v1.2.0/doxygen/",
    }
breathe_default_project = "myproject"
```

I had to add the below, as without specifying `.xml` it would not find any of the XML files:

```
source_suffix = '.xml'
```

The master_doc is the default:

```
master_doc = 'index'
```

After running

```
make html
```

I get the following error when it begins to write the HTML output:

```
# Sphinx version: 1.1.3
# Python version: 2.7.3
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 292, in write
    self.write_doc(docname, doctree)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/html.py", line 426, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/html.py", line 728, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/lib/python2.7/dist-packages/sphinx/jinja2glue.py", line 128, in render
    return self.environment.get_template(template).render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/share/sphinx/themes/basic/page.html", line 10, in top-level template code
    {% extends "layout.html" %}
  File "/usr/local/lib/python2.7/dist-packages/sphinx_rtd_theme/layout.html", line 90, in top-level template code
    {% set toctree = toctree(maxdepth=2, collapse=False, includehidden=True) %}
  File "/usr/lib/python2.7/dist-packages/jinja2/sandbox.py", line 349, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/html.py", line 720, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/html.py", line 656, in _get_local_toctree
    docname, self, collapse, **kwds))['fragment']
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 1180, in get_toctree_for
    doctree = self.get_doctree(self.config.master_doc)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 1213, in get_doctree
    f = open(doctree_filename, 'rb')
IOError: [Errno 2] No such file or directory: '/home/vagrant/itc/releases/v1.2.0/_build/doctrees/index.doctree'
```

**Comment by dnelson86** [comment]
Hi,

Thanks for this great project, I am just starting to use it. I've just also ran into this issue of wanting to have support for the `todo.xml` output of Doxygen.

For me, a `doxygentodo::` directive which simply listed them (all) out would be perfect. 

How can we proceed?

**Comment by vitaut** [comment]
Basically one has to create and register a new directive class, say `DoxygenTODODirective`. I think `DoxygenIndexDirective` is the closest to what's needed for the TODO directive because it also reads an XML file (`index.xml`) so maybe it can be used as a starting point. Rendering might need some tweaks too.
