### ISSUE TITLE
"Too many values to unpack" error

### ISSUE THREAD

**Issue by bocajnotnef** [michaeljones/breathe#261]
Hello,

Several months back I set up breathe, sphinx and doxygen on a project I'm a collaborator for, and it worked fantasitcally. Unfortunately I was unable to contribute to the project for some time. When I came back to it I attempted to rebuild the documentation only to get this error:

```
File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/index.py", line 43, in render_signature
    signode, contentnode = node.children
```

Nothing in the configuration for the documentation engines has changed and I can't seem to find any results for this error posted anywhere.

I'm using docutils v. 0.12, sphinx 1.4.1, doxygen 1.8.10 and Breathe 4.2.0.

Any suggestions on how to fix or where to look would be appreciated!

The full traceback is:

```
# Sphinx version: 1.4.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   updating environment:
#   15 added, 0 changed, 0 removed
#   reading sources... [  6%] dev/adding-documentation
#   reading sources... [ 13%] dev/contribution-guidelines-and-review
#   reading sources... [ 20%] dev/getting-started
#   reading sources... [ 26%] dev/guide-to-testing
#   reading sources... [ 33%] dev/index
#   reading sources... [ 40%] index
#   reading sources... [ 46%] library/config
#   reading sources... [ 53%] library/emtools
# Loaded extensions:
#   breathe (4.2.0) from /home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/__init__.pyc
#   sphinx.ext.todo (1.4.1) from /home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   alabaster (0.7.8) from /home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.pngmath (1.4.1) from /home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/ext/pngmath.pyc
Traceback (most recent call last):
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/environment.py", line 548, in update
    self._read_serial(docnames, app)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/environment.py", line 568, in _read_serial
    self.read_doc(docname, app)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/environment.py", line 721, in read_doc
    pub.publish()
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/sphinx/io.py", line 49, in read
    self.parse()
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/directive/file.py", line 92, in run
    return self.handle_contents(file_, project_info)
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/directive/file.py", line 62, in handle_contents
    node_list.extend(object_renderer.render())
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 144, in render
    nodelist.extend(renderIterable(self, self.data_object.innernamespace))
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 21, in renderIterable
    output.extend(child_renderer.render())
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/index.py", line 63, in render
    rendered_data = data_renderer.render()
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 39, in render
    return compound_renderer.render()
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 144, in render
    nodelist.extend(renderIterable(self, self.data_object.innernamespace))
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 21, in renderIterable
    output.extend(child_renderer.render())
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/index.py", line 63, in render
    rendered_data = data_renderer.render()
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 39, in render
    return compound_renderer.render()
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 143, in render
    nodelist.extend(renderIterable(self, self.data_object.innerclass))
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 21, in renderIterable
    output.extend(child_renderer.render())
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/index.py", line 71, in render
    nodes, contentnode = self.render_signature(file_data, self.create_doxygen_target())
  File "/home/jgf/git/Empirical/third-party/env/local/lib/python2.7/site-packages/breathe/renderer/index.py", line 43, in render_signature
    signode, contentnode = node.children
ValueError: too many values to unpack
```

**Comment by michaeljones** [comment]
Thanks for using Breathe. Is the project open source? Is this something we can reproduce?

**Comment by bocajnotnef** [comment]
Yep!

The project can be found at https://github.com/devosoft/Empirical

**Comment by bocajnotnef** [comment]
Yep! The project can be found at https://github.com/devosoft/Empirical

Fastest way to reproduce, assuming you have the doxygen dependencies and python-virtualenv installed:

```
git clone https://github.com/devosoft/Empirical.git
cd Empirical
# the following command will download & build doxygen and create the virtualenv 
# with the rest of the python packages we will need; sphinx, breathe, etc.
make install-dependencies
source third-party/env/bin/activate
make doc
```

**Comment by bocajnotnef** [comment]
Yep--The project can be found at https://github.com/devosoft/Empirical

Fastest route to reproduce:

```

```

**Comment by vitaut** [comment]
@bocajnotnef Could you check if it happens on `master` and submit an updated traceback? This (or similar issue) have been fixed in https://github.com/michaeljones/breathe/pull/239/commits/63dd7280304c458abf4661b3af292eea6d4f0beb.

**Comment by bocajnotnef** [comment]
Building from master removes the issue--I'll just update our script to grab from github instead of the old release.

Thanks!
