### ISSUE TITLE
Issue with 4.13.0 : parse_declaration() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by pramodk** [michaeljones/breathe#431]
Hello,

I am seeing following error:

```
Exception occurred:
  File "/gpfs/bbp.cscs.ch/home/kumbhar/tmp/nmodl/.eggs/breathe-4.13.0-py3.6.egg/breathe/renderer/sphinxrenderer.py", line 47, in parse_definition
    ast = parser.parse_declaration("class", "class")
TypeError: parse_declaration() takes 2 positional arguments but 3 were given
The full traceback has been saved in /tmp/sphinx-err-2xw5cegt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "setup.py", line 155, in <module>
    tests_require=["pytest>=3.7.2"],
  File "/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/serial-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/py-setuptools-40.4.3-fowpct5dsb/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/external-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-ukuow6gd2f/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/external-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-ukuow6gd2f/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/external-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-ukuow6gd2f/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 131, in run
    subprocess.check_call([sys.executable, __file__, "doctest"])
  File "/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/external-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-ukuow6gd2f/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/external-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-ukuow6gd2f/bin/python', 'setup.py', 'doctest']' returned non-zero exit status 1.
```

As I am seeing this since last two days, I wonder if this is related to latest release.

**Comment by svenevs** [comment]
What version of Sphinx are you using? I'm hopeful that this one is easy, changes to adapt to Sphinx 2.x were included in the latest release, but I don't know if they are 100% compatible with sphinx 1.x.

If you are not using Sphinx 2.x, does the error away if you update? If so then we should update

https://github.com/michaeljones/breathe/blob/bb33b576db6e55037cbd3a18d3582d376b47ebee/setup.py#L20

**Comment by rouault** [comment]
I'm having the same issue with Sphinx 1.8.5 / Python 2. See https://travis-ci.com/OSGeo/proj.4/jobs/194629602. Perhaps breathe 4.13.0 shouldn't be declared as Python 2 compatible

**Comment by melvinvermeeren** [comment]
Could someone with some Wheels experience check if the above PR looks fine. The intention is to drop python2 support and depend on sphinx 2.

If this is ok I will make a v4.13.0-post0 which should override v4.13.0 for PyPI, meaning v4.12.0 is the last version for use with python 2 and sphinx 1 and this should be resolved by package managers as such.

**Comment by pramodk** [comment]
> What version of Sphinx are you using?

We have Sphinx v1.8.5

> If you are not using Sphinx 2.x, does the error away if you update?

Will give a try.

By the way, I am using Python 3.6.5 (so this is not related to Python 2 I believe).

**Comment by larsgeb** [comment]
Same issues with Sphinx 1.8 and Python 3.7.

**Comment by melvinvermeeren** [comment]
v4.13.0.post0 has been released, which is marked as python 3 only and depends on Sphinx 2.

Can someone using python2 and/or sphinx 1 test the behaviour of pip or similar? It should now fetch breathe v4.12.0. Let me know if it fetches v4.13.0, I'll have to remove that version from PyPI in that case.

**Comment by alfredodeza** [comment]
Would love to see the version numbers tracking non-backwards compatibility. Will test with 4.12.0 and report back

**Comment by melvinvermeeren** [comment]
Regarding versioning, as just posted in #433. (Posting here to clarify for this issue.)

>Breathe itself has not changed any commands, logic or configuration options, meaning it is backwards compatible with previous versions. Because of this I believe the major version should stay the same.

**Comment by jakobandersen** [comment]
A bit of clarification: It is my understanding that Sphinx only supports the newest version (i.e., currently v2.0.1), which is how it has been for a long time. As I maintain the C++ domain in Sphinx I made PR #411 as an attempt at updating Breathe to work with a supported Sphinx version, where I unfortunately missed a bit (#432). The changes I suggested for Breathe did not attempt to be backwards compatible.
Note also that Python 2 it self is only supported throughout 2019.

**Comment by alfredodeza** [comment]
Thanks for the clarification @melvinvermeeren !

**Comment by melvinvermeeren** [comment]
@jakobandersen Yes, I share this view. Generally speaking I also expect that people that pin Sphinx to also pin extensions to versions that have been released around the same time as many extensions closely follow changes in Sphinx and integration is tight at times. Eventually things drift apart too far and issues will occur when partial pinning is used.

In hindsight I should have noticed this during review of #411, as you had (correctly) removed python < 3.5:
https://github.com/michaeljones/breathe/pull/411/files#diff-354f30a63fb0907d4ad57269548329e3L8.
Correct version management is my responsibility after all.

**Comment by svenevs** [comment]
Thanks for fixing @melvinvermeeren!

It works mostly as expected:

```console
sven:~> pip install breathe
Collecting breathe
  Downloading https://files.pythonhosted.org/packages/74/83/05c2045d0fc2af9f25d4c7915b78f2109a550c86abe7eb43b3aa36eb5ef0/breathe-4.13.0.post0.tar.gz (69kB)
    100% |████████████████████████████████| 71kB 670kB/s
    Complete output from command python setup.py egg_info:
    ERROR: Sphinx requires at least Python 3.5 to run.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y2/c8cgwl8j5csghq_vj4h91_fh0000gn/T/pip-install-Vfa722/breathe/
sven:~> pip3 install breathe
Collecting breathe
  Downloading https://files.pythonhosted.org/packages/36/03/e0c84ed0952902d042b77898b3631cb3aaf21f3d7a83c0e2ffa56f811ad0/breathe-4.13.0.post0-py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 743kB/s
```

Emphasis: **breathe-4.13.0.post0-py3-none-any.whl**, that's definitely what we want :tada:

It won't choose 4.12 with py2, but I don't view that as our problem.  People using py2 need to pin sphinx to 1.8.5 or below, and breathe to 4.12.

> Correct version management is my responsibility after all.

I reviewed the PR twice (once initial, once recent) and overlooked this both times x0

P.S. `breathe` is available on [Test PyPi](https://test.pypi.org/search/?q=breathe)

**Comment by melvinvermeeren** [comment]
I expected pip would be smarter than this, apparently not. Thanks for testing.
