### ISSUE TITLE
Mathbase module missing

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [michaeljones/breathe#436]
Breathe expects mathbase from `Sphinx.ext` module. I'm using latest breathe (built from source) and sphinx 3.0

```
# Sphinx version: 3.0.0+/f4d728b
# Python version: 3.6.7 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/mav/.local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/mav/.local/lib/python3.6/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/mav/.local/lib/python3.6/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/mav/.local/lib/python3.6/site-packages/sphinx/registry.py", line 432, in load_extension
    metadata = mod.setup(app)
  File "../breathe/breathe/__init__.py", line 13, in setup
    from . import directives
  File "../breathe/breathe/directives.py", line 4, in <module>
    from .renderer import DoxygenToRstRendererFactory
  File "../breathe/breathe/renderer/__init__.py", line 4, in <module>
    from ..node_factory import create_node_factory
  File "../breathe/breathe/node_factory.py", line 5, in <module>
    import sphinx.ext.mathbase
ModuleNotFoundError: No module named 'sphinx.ext.mathbase'
```

I'm new to using Breathe so if I'm doing something wrong let me know. I followed the quick start guide.

**Comment by melvinvermeeren** [comment]
Sphinx 3 is currently in development and not a released version. I believe current work is on sphinx 2 as this has been released rather recently. If the time between major versions is somewhat consistent it should stay at 2 for a few years at least.

As for the error: Sphinx's changelog[1] for 3 lists

>Incompatible changes
>--------------------
>
>* Drop features and APIs deprecated in 1.8.x

mathbase is probably one of them.

[1] https://github.com/sphinx-doc/sphinx/blob/master/CHANGES

**Comment by TheMaverickProgrammer** [comment]
Switching to 2.0 branch and downgrading Sphinx version solved issue
