### ISSUE TITLE
AttributeError: module 'sphinx.domains.c' has no attribute 'CMacroObject'

### ISSUE THREAD

**Issue by jedbrown** [michaeljones/breathe#495]
This just showed up on upgrade to v4.15.0; cf. cee5cd1e068d7ce16b7ed0ffd55c46fa5468b609

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 397, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 465, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/breathe/__init__.py", line 13, in setup
    from . import directives
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/breathe/directives.py", line 4, in <module>
    from .renderer import DoxygenToRstRendererFactory
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/breathe/renderer/__init__.py", line 5, in <module>
    from . import sphinxrenderer
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 74, in <module>
    class DomainDirectiveFactory(object):
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 90, in DomainDirectiveFactory
    'define': (c.CMacroObject, 'macro'),
AttributeError: module 'sphinx.domains.c' has no attribute 'CMacroObject'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 90, in DomainDirectiveFactory
    'define': (c.CMacroObject, 'macro'),
AttributeError: module 'sphinx.domains.c' has no attribute 'CMacroObject'
```

**Comment by vermeeren** [comment]
Breathe >= 4.15.0 explicitly requires Sphinx >= 3.0, as can be seen in https://github.com/michaeljones/breathe/blob/v4.15.0/setup.py#L18. I suppose you are force-installing things somehow and/or are ignoring dependency versions. Sphinx 3.0.0 definitely has `CMacroObject`.

**Comment by jedbrown** [comment]
Thanks. I expect other people will encounter this on ReadTheDocs where the default Sphinx is even older. Our requirements.txt only had `sphinx==2.4.4` and no version restriction on Breathe.

**Comment by vermeeren** [comment]
Thing is it should refuse to install in such a case, as the dependency cannot be satisfied, for example on https://github.com/microsoft/LightGBM/pull/2982 the resulting error is:

> ERROR: breathe 4.15.0 has requirement Sphinx>=3.0, but you'll have sphinx 2.4.4 which is incompatible.

I expect `pip` and others to handle this in a similar fashion unless dependencies are ignored, either pulling in an old version of Breathe when Sphinx is pinned to 2.x or giving a proper dependency error. It could be some tools used to manage packages do not check dependencies though.
