### ISSUE TITLE
NotImplementedError using doxygenfile

### ISSUE THREAD

**Issue by alephzero** [michaeljones/breathe#497]
Using
```rst
.. doxygenfile:: foo.h
```
with a nonexistent file results in the expected error in the generated html:
```
Warning
doxygenfile: Cannot find file “foo.h
```

If I set an existing file
```rst
.. doxygenfile:: packet.h
```
sphinx crashes with the following log below:

<details>
<summary>Crash log</summary>

```py
Running Sphinx v3.0.0
loading translations [en]... done
making output directory... done
Adding custom extension mapping: .h will be treated as language c
Adding custom extension mapping: .hpp will be treated as language c++
Adding custom extension mapping: .py will be treated as language python
Notice: Output directory `doxygen_build' does not exist. I have created it for you.
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...
Searching for files in directory /home/docs/alephzero/include
Searching for files in directory /home/docs/alephzero/include/a0
Reading and parsing tag files
Parsing files
Preprocessing /home/docs/alephzero/include/a0/alephzero.hpp...
Parsing file /home/docs/alephzero/include/a0/alephzero.hpp...
Preprocessing /home/docs/alephzero/include/a0/alloc.h...
Parsing file /home/docs/alephzero/include/a0/alloc.h...
Preprocessing /home/docs/alephzero/include/a0/common.h...
Parsing file /home/docs/alephzero/include/a0/common.h...
Preprocessing /home/docs/alephzero/include/a0/logger.h...
Parsing file /home/docs/alephzero/include/a0/logger.h...
Preprocessing /home/docs/alephzero/include/a0/packet.h...
Parsing file /home/docs/alephzero/include/a0/packet.h...
Preprocessing /home/docs/alephzero/include/a0/prpc.h...
Parsing file /home/docs/alephzero/include/a0/prpc.h...
Preprocessing /home/docs/alephzero/include/a0/pubsub.h...
Parsing file /home/docs/alephzero/include/a0/pubsub.h...
Preprocessing /home/docs/alephzero/include/a0/rpc.h...
Parsing file /home/docs/alephzero/include/a0/rpc.h...
Preprocessing /home/docs/alephzero/include/a0/shm.h...
Parsing file /home/docs/alephzero/include/a0/shm.h...
Preprocessing /home/docs/alephzero/include/a0/shm_sync.h...
Parsing file /home/docs/alephzero/include/a0/shm_sync.h...
Preprocessing /home/docs/alephzero/include/a0/time.h...
Parsing file /home/docs/alephzero/include/a0/time.h...
Preprocessing /home/docs/alephzero/include/a0/topic_manager.h...
Parsing file /home/docs/alephzero/include/a0/topic_manager.h...
Preprocessing /home/docs/alephzero/include/a0/transport.h...
Parsing file /home/docs/alephzero/include/a0/transport.h...
Preprocessing /home/docs/alephzero/include/a0.h...
Parsing file /home/docs/alephzero/include/a0.h...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Associating documentation with classes...
Computing nesting relations for classes...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Creating members for template instances...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Sorting lists...
Freeing entry tree
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Computing dependencies between directories...
Generating citations page...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Generating style sheet...
Generating search indices...
Generating example documentation...
Generating file sources...
Generating code for file /home/docs/alephzero/include/a0.h...
Generating code for file /home/docs/alephzero/include/a0/alephzero.hpp...
Generating code for file /home/docs/alephzero/include/a0/alloc.h...
Generating code for file /home/docs/alephzero/include/a0/common.h...
Generating code for file /home/docs/alephzero/include/a0/logger.h...
Generating code for file /home/docs/alephzero/include/a0/packet.h...
Generating code for file /home/docs/alephzero/include/a0/prpc.h...
Generating code for file /home/docs/alephzero/include/a0/pubsub.h...
Generating code for file /home/docs/alephzero/include/a0/rpc.h...
Generating code for file /home/docs/alephzero/include/a0/shm.h...
Generating code for file /home/docs/alephzero/include/a0/shm_sync.h...
Generating code for file /home/docs/alephzero/include/a0/time.h...
Generating code for file /home/docs/alephzero/include/a0/topic_manager.h...
Generating code for file /home/docs/alephzero/include/a0/transport.h...
Generating file documentation...
Generating docs for file /home/docs/alephzero/include/a0.h...
Generating docs for file /home/docs/alephzero/include/a0/alephzero.hpp...
Generating docs for file /home/docs/alephzero/include/a0/alloc.h...
Generating docs for file /home/docs/alephzero/include/a0/common.h...
Generating docs for file /home/docs/alephzero/include/a0/logger.h...
Generating docs for file /home/docs/alephzero/include/a0/packet.h...
Generating docs for file /home/docs/alephzero/include/a0/prpc.h...
Generating docs for file /home/docs/alephzero/include/a0/pubsub.h...
Generating docs for file /home/docs/alephzero/include/a0/rpc.h...
Generating docs for file /home/docs/alephzero/include/a0/shm.h...
Generating docs for file /home/docs/alephzero/include/a0/shm_sync.h...
Generating docs for file /home/docs/alephzero/include/a0/time.h...
Generating docs for file /home/docs/alephzero/include/a0/topic_manager.h...
Generating docs for file /home/docs/alephzero/include/a0/transport.h...
Generating page documentation...
Generating group documentation...
Generating class documentation...
Generating docs for compound a0_alloc_s...
Generating docs for compound a0_buf_s...
Generating docs for compound a0_callback_s...
Generating docs for compound a0_locked_transport_s...
Generating docs for compound a0_logger_s...
Generating docs for compound a0_mtx_s...
Generating docs for compound a0_packet_callback_s...
Generating docs for compound a0_packet_header_callback_s...
Generating docs for compound a0_packet_header_s...
Generating docs for compound a0_packet_headers_block_s...
Generating docs for compound a0_packet_id_callback_s...
Generating docs for compound a0_packet_s...
Generating docs for compound a0_packet_stats_s...
Generating docs for compound a0_prpc_callback_s...
Generating docs for compound a0_prpc_client_s...
Generating docs for compound a0_prpc_connection_callback_s...
Generating docs for compound a0_prpc_connection_s...
Generating docs for compound a0_prpc_server_s...
Generating docs for compound a0_publisher_s...
Generating docs for compound a0_rpc_client_s...
Generating docs for compound a0_rpc_request_callback_s...
Generating docs for compound a0_rpc_request_s...
Generating docs for compound a0_rpc_server_s...
Generating docs for compound a0_shm_options_s...
Generating docs for compound a0_shm_s...
Generating docs for compound a0_subscriber_s...
Generating docs for compound a0_subscriber_sync_s...
Generating docs for compound a0_subscriber_sync_zc_s...
Generating docs for compound a0_subscriber_zc_s...
Generating docs for compound a0_topic_alias_s...
Generating docs for compound a0_topic_manager_s...
Generating docs for compound a0_transport_frame_hdr_s...
Generating docs for compound a0_transport_frame_s...
Generating docs for compound a0_transport_s...
Generating docs for compound a0_zero_copy_callback_s...
Generating namespace index...
Generating docs for namespace a0
Generating docs for compound a0::Logger...
Generating docs for compound a0::Packet...
Generating docs for compound a0::PacketView...
Generating docs for compound a0::PrpcClient...
Generating docs for compound a0::PrpcConnection...
Generating docs for compound a0::PrpcServer...
Generating docs for compound a0::Publisher...
Generating docs for compound a0::RpcClient...
Generating docs for compound a0::RpcRequest...
Generating docs for compound a0::RpcServer...
Generating docs for compound a0::Shm...
Generating docs for nested compound a0::Shm::Options...
Generating docs for compound a0::Subscriber...
Generating docs for compound a0::SubscriberSync...
Generating docs for compound a0::TopicAliasTarget...
Generating docs for compound a0::TopicManager...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
Generating XML output...
Generating XML output for class a0_alloc_s
Generating XML output for class a0_buf_s
Generating XML output for class a0_callback_s
Generating XML output for class a0_locked_transport_s
Generating XML output for class a0_logger_s
Generating XML output for class a0_mtx_s
Generating XML output for class a0_packet_callback_s
Generating XML output for class a0_packet_header_callback_s
Generating XML output for class a0_packet_header_s
Generating XML output for class a0_packet_headers_block_s
Generating XML output for class a0_packet_id_callback_s
Generating XML output for class a0_packet_s
Generating XML output for class a0_packet_stats_s
Generating XML output for class a0_prpc_callback_s
Generating XML output for class a0_prpc_client_s
Generating XML output for class a0_prpc_connection_callback_s
Generating XML output for class a0_prpc_connection_s
Generating XML output for class a0_prpc_server_s
Generating XML output for class a0_publisher_s
Generating XML output for class a0_rpc_client_s
Generating XML output for class a0_rpc_request_callback_s
Generating XML output for class a0_rpc_request_s
Generating XML output for class a0_rpc_server_s
Generating XML output for class a0_shm_options_s
Generating XML output for class a0_shm_s
Generating XML output for class a0_subscriber_s
Generating XML output for class a0_subscriber_sync_s
Generating XML output for class a0_subscriber_sync_zc_s
Generating XML output for class a0_subscriber_zc_s
Generating XML output for class a0_topic_alias_s
Generating XML output for class a0_topic_manager_s
Generating XML output for class a0_transport_frame_hdr_s
Generating XML output for class a0_transport_frame_s
Generating XML output for class a0_transport_s
Generating XML output for class a0_zero_copy_callback_s
Generating XML output for class a0::Logger
Generating XML output for class a0::Shm::Options
Generating XML output for class a0::Packet
Generating XML output for class a0::PacketView
Generating XML output for class a0::PrpcClient
Generating XML output for class a0::PrpcConnection
Generating XML output for class a0::PrpcServer
Generating XML output for class a0::Publisher
Generating XML output for class a0::RpcClient
Generating XML output for class a0::RpcRequest
Generating XML output for class a0::RpcServer
Generating XML output for class a0::Shm
Generating XML output for class a0::Subscriber
Generating XML output for class a0::SubscriberSync
Generating XML output for class a0::TopicAliasTarget
Generating XML output for class a0::TopicManager
Generating XML output for namespace a0
Generating XML output for namespace std
Generating XML output for file a0.h
Generating XML output for file alephzero.hpp
Generating XML output for file alloc.h
Generating XML output for file common.h
Generating XML output for file logger.h
Generating XML output for file packet.h
Generating XML output for file prpc.h
Generating XML output for file pubsub.h
Generating XML output for file rpc.h
Generating XML output for file shm.h
Generating XML output for file shm_sync.h
Generating XML output for file time.h
Generating XML output for file topic_manager.h
Generating XML output for file transport.h
Generate XML output for dir /home/docs/alephzero/include/a0/
Generate XML output for dir /home/docs/alephzero/include/
lookup cache used 959/65536 hits=9019 misses=1067
finished...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 2 source files that are out of date
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [ 50%] index
reading sources... [100%] packet
/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/deprecation.py:49: RemovedInSphinx40Warning: sphinx.builders.html.DirectoryHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  return getattr(self._module, name)
/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/readthedocs_ext/readthedocs.py:14: RemovedInSphinx40Warning: sphinx.builders.html.SingleFileHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  from sphinx.builders.html import (DirectoryHTMLBuilder, SingleFileHTMLBuilder,

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/directive/file.py", line 91, in run
    return self.handle_contents(file_, project_info)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/directive/file.py", line 61, in handle_contents
    node_list.extend(object_renderer.render(node_stack[0], context))
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1308, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 617, in visit_compounddef
    child_nodes = self.render(sectiondef)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1308, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 651, in visit_sectiondef
    node_list.extend(self.render_iterable(node.memberdef))
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1318, in render_iterable
    output.extend(self.render(entry))
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1308, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1253, in dispatch_memberdef
    return self.visit_define(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1050, in visit_define
    return self.render_declaration(node, declaration, update_signature=update_define_signature)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 412, in render_declaration
    nodes = self.run_domain_directive(obj_type, [declaration.replace('\n', ' ')])
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 357, in run_domain_directive
    nodes = domain_directive.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/domains/c.py", line 3079, in run
    return super().run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/directives/__init__.py", line 190, in run
    name = self.handle_signature(sig, signode)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/domains/c.py", line 3086, in handle_signature
    ast = self.parse_definition(parser)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/domains/c.py", line 3063, in parse_definition
    return parser.parse_declaration(self.object_type, self.objtype)
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/domains/c.py", line 3053, in object_type
    raise NotImplementedError()
NotImplementedError

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/alephzero/envs/latest/lib/python3.7/site-packages/sphinx/domains/c.py", line 3053, in object_type
    raise NotImplementedError()
NotImplementedError
```
</details>

**Comment by vermeeren** [comment]
Can you post the contents of the `foo.h` that triggers the bug?

**Comment by alephzero** [comment]
I kept thinking it was the `@file` comment at the top but it's not.

The offending lines seem to be:
```cc
#define A0_PACKET_ID_SIZE 37
typedef char a0_packet_id_t[A0_PACKET_ID_SIZE];
```

**Comment by vermeeren** [comment]
Can you confirm that if those lines are removed the directive works? If so, and based upon the crash log, I suspect this is actually a bug in Sphinx's C domain. Probably just an unhandled (edge) case somewhere.

@jakobandersen could you check if you have some time?

**Comment by jakobandersen** [comment]
Which version of Breathe is being used? From the stack trace it looks like it's not the newest version, which is the only one that works with Sphinx 3.

**Comment by alephzero** [comment]
@vermeeren 
replacing those two lines with the following works:
```cc
typedef char a0_packet_id_t[37];
```

@jakobandersen 
I'm pip installing `breathe==4.14.1`

**Comment by jakobandersen** [comment]
You will need 4.15 to use Sphinx 3.0.

**Comment by vermeeren** [comment]
@jakobandersen to prevent similar issues in the future I am considering putting `Sphinx>=3.0,<4` in the `setup.py`, which should work according to https://packaging.python.org/discussions/install-requires-vs-requirements/. Do you think this is a good idea?

**Comment by jakobandersen** [comment]
@vermeeren, I'm not sure. If I understand correctly, then the worst thing that can happen with this version constraint is that there for sure needs to be a (dummy) update of Breathe at the time?
Technically, Breathe relies on a lot of undocumented behaviour so there are no guarantees that it will not break in any new version, so you may even consider putting 3.1 as the upper bound if you don't mind making new releases every few months.

**Comment by vermeeren** [comment]
> If I understand correctly, then the worst thing that can happen with this version constraint is that there for sure needs to be a (dummy) update of Breathe at the time?

Correct.

> so you may even consider putting 3.1 as the upper bound if you don't mind making new releases every few months.

Sounds good to me, this way at least Breathe's CICD will have to pass with the new Sphinx version prior to having it released. Hopefully this can prevent the majority of obvious breakage.

I will fixup a patch in a bit and will @jakobandersen you there.

**Comment by lshamis** [comment]
4.15 works for me

**Comment by lshamis** [comment]
Thanks for the quick response!

**Comment by lshamis** [comment]
Just noticed I switched accounts. To prevent confusion, I am @alephzero

**Comment by vermeeren** [comment]
Thanks for the update.
