### ISSUE TITLE
Sphinx fails when dealing with complex templates

### ISSUE THREAD

**Issue by AkibAzmain** [michaeljones/breathe#611]
I'm developing a template rich library. For generating documentation I use Breathe and Exhale (both latest). My library has a function like this:

```c++
/**
 * @brief Raises an exception
 * 
 * @details @rst
 * 
 * This function throws or raises an exception. The exception must
 * derive from :class:`py::core::BaseException`.
 * 
 * @endrst
 * 
 * @tparam type type of the exception, must be a derived class of
 * BaseException
 * 
 * @param exception the exception to raise
 */
template <
    class type,
    class = decltype(
        static_cast<BaseException*>(static_cast<type*>(0))
    )
>
[[noreturn]] void raise(type& exception)
{
    throw exception;
}
```

By parsing Doxygen output, Exhale generates the following directive which is perfectly valid:

```rst
.. doxygenfunction:: py::core::raise(const type&)
```

But when I try to generate documentations, I get the following error:

```
Exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/sphinx/util/cfamily.py", line 293, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name, got keyword: static_cast [error at 12]
  (static_cast<BaseException*>(static_cast<type*>(0)))> void raise(type &exception)
  ------------^
The full traceback has been saved in /tmp/sphinx-err-q2z6msxp.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Generated traceback file by Sphinx:

```
# Sphinx version: 3.3.1
# Python version: 3.8.5 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   reading sources... [ 47%] api/function_list_8hpp_1a4d3b3ba5a4198027254aee727e20b384
#   reading sources... [ 49%] api/function_list_8hpp_1a57f5e1c4aaed434f69d7129d4b971956
#   reading sources... [ 50%] api/function_list_8hpp_1a9debc04ce86e2e45b169013a85fd46d6
#   reading sources... [ 52%] api/function_list_8hpp_1ad627d5af1fa35c0a21a2f9cda388fa7b
#   reading sources... [ 53%] api/function_list_8hpp_1ae9e02d3c3c6551649c4a657eb0b14282
#   reading sources... [ 55%] api/function_max_8hpp_1a187e1c13280ee29cd9ba55e115cb75e7
#   reading sources... [ 56%] api/function_max_8hpp_1a7fef79ca2806934ea5cabd4210ed85fd
#   reading sources... [ 58%] api/function_min_8hpp_1aa79838d02f9a2b1d01cb772799f11792
#   reading sources... [ 60%] api/function_min_8hpp_1ae0179a26d1ef688a89293e583a5c3add
#   reading sources... [ 61%] api/function_raise_8hpp_1a1835ba2a4efcd257b8824b153c4a02bd
# Loaded extensions:
#   sphinx.ext.mathjax (3.3.1) from /usr/local/lib/python3.8/dist-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.8/dist-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.8/dist-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /usr/local/lib/python3.8/dist-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /usr/local/lib/python3.8/dist-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.8/dist-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   sphinx.ext.graphviz (3.3.1) from /usr/local/lib/python3.8/dist-packages/sphinx/ext/graphviz.py
#   breathe (4.25.1) from /usr/local/lib/python3.8/dist-packages/breathe/__init__.py
#   exhale (0.2.3) from /usr/local/lib/python3.8/dist-packages/exhale/__init__.py
#   sphinx_rtd_theme (unknown version) from /usr/lib/python3/dist-packages/sphinx_rtd_theme/__init__.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.8/dist-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.8/dist-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.8/dist-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/local/lib/python3.8/dist-packages/sphinx/io.py", line 223, in read_doc
    pub.publish()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/local/lib/python3.8/dist-packages/sphinx/io.py", line 128, in read
    self.parse()
  File "/usr/lib/python3/dist-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2770, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2770, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2343, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2355, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2097, in directive
    return self.run_directive(
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2147, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python3.8/dist-packages/breathe/directives.py", line 99, in run
    node_stack = self.resolve_function(matches, args, project_info)
  File "/usr/local/lib/python3.8/dist-packages/breathe/directives.py", line 231, in resolve_function
    match_args = self.parse_args(_match_args)
  File "/usr/local/lib/python3.8/dist-packages/breathe/directives.py", line 147, in parse_args
    paramQual = parser._parse_parameters_and_qualifiers(paramMode='function')
  File "/usr/local/lib/python3.8/dist-packages/sphinx/domains/cpp.py", line 5682, in _parse_parameters_and_qualifiers
    arg = self._parse_type_with_init(outer=None, named='single')
  File "/usr/local/lib/python3.8/dist-packages/sphinx/domains/cpp.py", line 6175, in _parse_type_with_init
    type = self._parse_type(outer=outer, named=named)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/domains/cpp.py", line 6166, in _parse_type
    declSpecs = self._parse_decl_specs(outer=outer)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/domains/cpp.py", line 5860, in _parse_decl_specs
    trailing = self._parse_trailing_type_spec()
  File "/usr/local/lib/python3.8/dist-packages/sphinx/domains/cpp.py", line 5656, in _parse_trailing_type_spec
    nestedName = self._parse_nested_name()
  File "/usr/local/lib/python3.8/dist-packages/sphinx/domains/cpp.py", line 5582, in _parse_nested_name
    self.fail("Expected identifier in nested name, "
  File "/usr/local/lib/python3.8/dist-packages/sphinx/util/cfamily.py", line 293, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name, got keyword: static_cast [error at 12]
  (static_cast<BaseException*>(static_cast<type*>(0)))> void raise(type &exception)
  ------------^

```

**Comment by vermeeren** [comment]
@AkibAzmain At a glance I believe this is an issue over at the Sphinx side, where Breathe eventually forwards things to. Could you report it over there and add a reference to this issue?

**Comment by jakobandersen** [comment]
I tried copying the original declaration from your C++ code
```rst
.. cpp:function:: template<class type, class = decltype(static_cast<BaseException*>(static_cast<type*>(0)))> \
                  [[noreturn]] void raise(type& exception)
```
and that works with Sphinx, so I think there is a problem somewhere in the Exhale/Breathe translation.
From your error output it looks like Sphinx is trying to parse
```c++
(static_cast<BaseException*>(static_cast<type*>(0)))> void raise(type &exception)
```
which is obviously missing a lot of the original declaration.

Do you have a not-too-large example project where you observe the error, that you can share?

**Comment by mquinson** [comment]
I was hit by a similar problem, where breathe fails to find the right overload when I have function signatures in my template parameters. I found a workaround by hiding this part from doxygen. Here is how I implemented that workaround:
```
  template <class F, class... Args,
#ifndef DOXYGEN /* breathe seem to choke on function signatures in template parameter */
            typename = typename std::result_of_t<F(Args...)>
#endif
            >
  static ActorPtr create(const std::string& name, s4u::Host* host, F code, Args... args)
```

With this workaround, it works when I add this to my rst file:
```
      .. doxygenfunction:: simgrid::s4u::Actor::create(const std::string &name, s4u::Host *host, F code, Args... args)
```

Without the workaround, the same RST line produces the following error. The overload I'm trying to document is in the list, but I fail to select it from the RST without my workaround.
```
/home/mquinson/Code/simgrid/docs/source/app_s4u.rst:434: WARNING: doxygenfunction: Unable to resolve function "simgrid::s4u::Actor::create" with arguments (const std::string&, s4u::Host*, F, Args...) in doxygen xml output for project "simgrid" from directory: ../build/xml.                                                                                                         
Potential matches:                                                                                                                                                                           
- ActorPtr create(const std::string &name, s4u::Host *host, const std::function<void()> &code)                                                                                               
- ActorPtr create(const std::string &name, s4u::Host *host, const std::string &function, std::vector<std::string> args)                                                                      
- template<class F, class ...Args, typename = typename std::result_of_t<F(Args...)>> ActorPtr create(const std::string &name, s4u::Host *host, F code, Args... args)                         
- template<class F> ActorPtr create(const std::string &name, s4u::Host *host, F code)                                                                                                        ```

Here is the relevant excerpts of the XML (without the workaround):
```
      <memberdef kind="function" id="classsimgrid_1_1s4u_1_1Actor_1aff5c65ad19f76e440311d090dd4fc1b6" prot="public" static="yes" const="no" explicit="no" inline="yes" virt="non-virtual">
        <templateparamlist>
          <param>
            <type>class F</type>
          </param>
          <param>
            <type>class...</type>
            <declname>Args</declname>
            <defname>Args</defname>
          </param>
          <param>
            <type>typename</type>
            <defval>typename std::result_of_t&lt;F(Args...)&gt;</defval>
          </param>
        </templateparamlist>
        <type>ActorPtr</type>
        <definition>static ActorPtr simgrid::s4u::Actor::create</definition>
        <argsstring>(const std::string &amp;name, s4u::Host *host, F code, Args... args)</argsstring>
        <name>create</name>
        <param>
          <type>const std::string &amp;</type>
          <declname>name</declname>
        </param>
        <param>
          <type><ref refid="classsimgrid_1_1s4u_1_1Host" kindref="compound">s4u::Host</ref> *</type>
          <declname>host</declname>
        </param>
        <param>
          <type>F</type>
          <declname>code</declname>
        </param>
        <param>
          <type>Args...</type>
          <declname>args</declname>
        </param>
        <briefdescription>
```

As expected, my workaround produces the following change to the XML (plus some ID changes):
```
@@ -660,6 +660,10 @@
             <declname>Args</declname>
             <defname>Args</defname>
           </param>
-          <param>
-            <type>typename</type>
-            <defval>typename std::result_of_t&lt;F(Args...)&gt;</defval>
-          </param>
         </templateparamlist>
         <type>ActorPtr</type>
         <definition>static ActorPtr simgrid::s4u::Actor::create</definition>
```

Breathe v4.27.0, Sphinx v3.4.3 (both from pip3), doxygen v1.9.1-1 (Debian package)

**Comment by vermeeren** [comment]
From https://github.com/michaeljones/breathe/issues/663#issuecomment-809351599, this might be (partially) fixed with doxygen/doxygen#8465.
