### ISSUE TITLE
Pip Install Failure

### ISSUE THREAD

**Issue by cmshuang** [michaeljones/breathe#649]
Hello,

I get the following error when I run `pip install breathe`.
```
$ pip install breathe
Collecting breathe
  Using cached https://files.pythonhosted.org/packages/42/71/0e7f1aa530c4e5ec401eafbae3530afb6ef559ac39c651150e4900ce381b/breathe-4.27.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6BqRL4/breathe/setup.py", line 10, in <module>
        from breathe import __version__
      File "breathe/__init__.py", line 10
        def setup(app: Sphinx):
                     ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6BqRL4/breathe/
```
Please advise. Thank you!

**Comment by cmshuang** [comment]
Realized my system default python version was 2.7--works just fine when I changed it to 3.6, sorry!
